### ISSUE TITLE
The find_text_in_image method does not exist in image_handler, perhaps find_texts_in_image?

### ISSUE THREAD

**Issue by Philip-Wang01** [jieliu2000/RPALite#2]
![image](https://github.com/user-attachments/assets/8ca00173-4684-4cfe-a25e-379220eee3ad)
![image](https://github.com/user-attachments/assets/095abec2-28ce-450a-9df8-fce45a64b692)

**Comment by jieliu2000** [comment]
Hi @Philip-Wang01 , You are quite right. It should be find_texts_in_image(img, text). This has been fixed in 31ee7c4

**Comment by Philip-Wang01** [comment]
Verified this in the latest version and the issue has been fixed. So close it.
![image](https://github.com/user-attachments/assets/e635f23f-a5aa-44fa-8d18-1397988350f1)
