### ISSUE TITLE
Does RPALite need to add a method to copy text to the clipboard?

### ISSUE THREAD

**Issue by Philip-Wang01** [jieliu2000/RPALite#4]
If I want to write a code like this:
```
import pyperclip
pyperclip.copy("This is a test string.")
copied_text = pyperclip.paste()
print("Clipboard content:", copied_text)
```
Do I need to write it like this?
```
import pyperclip
pyperclip.copy("This is a test string.")
copied_text = self.rpalite.get_clipboard_text()
print("Clipboard content:", copied_text)
```

**Comment by jieliu2000** [comment]
Hi @Philip-Wang01 , yes we can have one method like that. If you want you can submit a pull request by yourself. Feel free to folk this repo and submit your changes via pull request to this repo. I

**Comment by Philip-Wang01** [comment]
@jieliu2000 Please review it: https://github.com/jieliu2000/RPALite/pull/6

**Comment by jieliu2000** [comment]
The changes have been merged
